# Video Parameters
video_model: "models/DT0F.pth"
video_num_episodes: 1
video_fps: 60
# Hyperparameters
num_steps: 5000000
num_processes: 1
num_mini_batch: 32
rollout_size: 2048
gamma: 0.99
learning_rate: 0.00005
ppo_epochs: 5
clip: 0.1
value_loss_coef: 0.5
entropy_coef: 0.01
max_grad_norm: 0.5
eps: 0.00001
sequential_model: "DecisionTransformer"
hidden_state_size: 512
context_window_size: 10
# Environment Parameters
observation_type: "RGBD"
large_map_size: 84
small_map_size: 84
large_map_range: 84
small_map_range: 42
grid_blocks_size: 0.25
agent_height: 1.5
agent_base: 0
agent_obstacle_height_tolerance: 0.15
obs_height: 84
obs_width: 84
environment_size: 6
num_hidden_rooms: 6 # Number of hidden rooms to generate
minimum_full_rooms: 0.9 # Minimum percentage of rooms that are generated
room_size: 7 
door_width: 2.2
door_height: 2.5
door_length: 0.5
max_episode_steps: 20000
coverage_for_termination: 0.95
step_penalty: 0.00001
depth_cutoff: 5
seed: 0 